### ISSUE TITLE
Test the code

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#18]
Use a test runner (I recommend [mocha](https://github.com/mochajs/mocha)) to test the scenarios we care about most.

This could be implemented together with the rework (#17) to ensure code changes do not affect the current behavior.

**Scenarios**

- [x] Rule including users and teams
- [x] Rule including users only
- [x] Rule including teams only
- [x] Users specified individually are asked individually even if they are members of a relevant team

**Configuration file**

- [x] Validate the configuration's structure

**Comment by TriplEight** [comment]
Good idea.
Also, we should check for misuses. How does it handle lists, at least space and comma-separated ones?
How does it handle conflicting rules, overlapping rules, no rules at all, etc.
Emojis mentioned in the rules and typed one right after another in the comment. Special symbols after these emojis, etc.

**Comment by TriplEight** [comment]
Also, how will it act if the action config was tampered with? I.e. checkout step was removed.

**Comment by joao-paulo-parity** [comment]
Regarding configuration validation, https://github.com/paritytech/pr-custom-review/commit/866181127d1969958569134f775a6f460928f962 should take care of that. If it doesn't work well for some reason then we can try another validation system, e.g. one based on JSON Schema. I went with Joi because it's seems simpler.

We could have a validation test using those schemas after the change lands.
