### ISSUE TITLE
Improve configuration file terminology

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#19]
In https://github.com/paritytech/pr-custom-review/pull/12 I'm trying to push for the term "rules" instead of "conditions", "groups", "checks", and the like, which seem to be used interchangeably currently. For instance, what's called "approval_groups" in the current configuration can simply be called "rules". This seems to have caused some confusion already in https://github.com/paritytech/pr-custom-review/issues/1#issue-1073657316:

> do user3 and user4 have to be from reviewers_group2?

That question does not make sense for the current implementation because "reviewers_group2" is the name of a "rule", not group.

**Comment by TriplEight** [comment]
Good catch, it's important to straighforward the terminology in the explanations.
"Rules" sounds better than "conditions" or "checks" or "approval_groups". "Teams" is a github native so "groups" should be phased out too.
