### ISSUE TITLE
Separate activity diagram into different diagrams for each event

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#20]
Inspired by https://github.com/paritytech/pr-custom-review/issues/1#issue-1073657316

> On Diagram: what's PRR? Pull Request Review?

It might be a good idea to separate the diagram into two flows for each event, that way it would not be necessary to create shorthands for the two different kinds of events.

If the diagram won't be separated then perhaps remove the shorthands, it's unnecessary.

Additionally the diagrams can be written in e.g. [PlantUML](https://plantuml.com/activity-diagram-beta), as demonstrated in https://github.com/paritytech/ci_cd/issues/162#issuecomment-1005074444, and have their source code committed to the repository.

**Comment by TriplEight** [comment]
PlantUML seems awesome, but don't you think this tool should not get more complicated than this?

**Comment by joao-paulo-parity** [comment]
The diagrams helps both non-developers and developers to quickly understand what the action does. Given that not only Parity developers, but also other users, since this is a public project, will be reading the documentation, for me it makes sense to care about maintaining them with the same care one would have for the features themselves.

I much prefer PlantUML over having a diagram which is not editable by open source contributors. It's not reasonable for me to open GIMP or whatever to edit the image manually. Above all I don't think PlantUML adds any meaningful complexity:

- It has decent documentation (https://plantuml.com/activity-diagram-legacy, https://plantuml.com/activity-diagram-beta, [many others](https://plantuml.com/sitemap-language-specification))
- The diagram can be committed as code to the repository, meaning anyone will be make changes trivially with a text editor
- It's open-source, unlike most online websites for generating diagrams

Absolutely I think it's worth it. If not PlantUML then any another code-to-diagram tool would do.

**Comment by TriplEight** [comment]
I'm not against it, this is a really net idea indeed! Just deprioritizing :)
