### ISSUE TITLE
Document why actions/checkout@v2 is needed

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#28]
I believe actions/checkout@v2 is not needed since we're pulling the diff and changed files from the GitHub API.

https://github.com/paritytech/pr-custom-review/blob/2c4afa8463f9d96d17a73cc7071a9aafe42ce5a4/src/main.ts#L171-L172

@sergejparity do you have some use-case in mind for that step?

In case it really is not needed, we should remove it from the documentation.

**Comment by sergejparity** [comment]
@joao-paulo-parity actually you're right. In earlier versions of this action I performed let's say that "manual" evaluation over the checked out code. But now it is useless.

**Comment by sergejparity** [comment]
Just one problem, config file could not be read: https://github.com/tripleightech/pr-custom-review-test/runs/4817666543?check_suite_focus=true

**Comment by joao-paulo-parity** [comment]
> Just one problem, config file could not be read: https://github.com/tripleightech/pr-custom-review-test/runs/4817666543?check_suite_focus=true

File contents can be read from the GitHub API using https://docs.github.com/en/rest/reference/repos#get-repository-content, so we don't ultimately need the `actions/checkout@v2` either way. We can leave that task as a future improvement and document the current usage of `actions/checkout@v2` in the meantime.

**Comment by joao-paulo-parity** [comment]
> > Just one problem, config file could not be read: https://github.com/tripleightech/pr-custom-review-test/runs/4817666543?check_suite_focus=true
> 
> File contents can be read from the GitHub API using https://docs.github.com/en/rest/reference/repos#get-repository-content, so we don't ultimately need the `actions/checkout@v2` either way. We can leave that task as a future improvement and document the current usage of `actions/checkout@v2` in the meantime.

Actually I am going to implement this for tests #18 since it's more convenient that way
