### ISSUE TITLE
Create the Locks Review Team

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#33]
Currently we are hardcoding the "touched locks" review team

https://github.com/paritytech/pr-custom-review/blob/2c4afa8463f9d96d17a73cc7071a9aafe42ce5a4/src/main.ts#L212

That has been made configurable with #31 which has not yet landed on master.

https://github.com/joao-paulo-parity/pr-custom-review/blob/8ecb5a1c513f1627c7675a511255157cea32613e/src/core.ts#L57

We are not able to install the action in the real repositories in case this team does not exist. In https://github.com/tripleightech/pr-custom-review-test it works because the [Locks Review Team already exists](https://github.com/tripleightech/pr-custom-review-test/blob/cd7eeeaa1d5abdc8db5ca7a4fee979f127c726a6/.github/workflows/pr_custom_review.yml#L27).

From https://github.com/paritytech/ci_cd/issues/233

> must have approvals from at least one team lead as well as either the CTO or the CEO

I suppose @TriplEight would be the one to create those teams, hence why I am assigning the task to him

**Comment by TriplEight** [comment]
Created a new team, added it in [the config](https://github.com/paritytech/substrate/pull/10951/files#diff-d20200289859b0e336bcc8f855c0166f804f02f08534c3f1abeeceda0e75abe5R24-R25).
