### ISSUE TITLE
Generate token for the paritytech organization

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#47]
Problem: We need a token for the workflow, as demonstrated in https://github.com/tripleightech/pr-custom-review-test/blob/9de8003ccd88d33c41d50259c3eefcc1dc3a7790/.github/workflows/pr_custom_review.yml#L26. [According to our README](https://github.com/paritytech/pr-custom-review/blob/9bd240b43fb17b4e0fb1933c792d545cc0ac5fe1/README.md?plain=1#L162), the token needs to have Organization read-only permissions for https://github.com/paritytech.

Alternatives:

- Create a permanent token in paritytech
- Create a Github App for pr-custom-review and generate the token at runtime using https://github.com/octokit/auth-app.js, like it's done e.g. on cla-bot (https://gitlab.parity.io/parity/opstooling/cla-bot-2021/-/blob/dc964fb7709a3112624bdb05126097ebb276147e/src/bot.ts#L77). If we were to go with this approach, the GitHub app of course has to be installed in the paritytech organization.

**Comment by Vovke** [comment]
@joao-paulo-parity please use `PRCR_TOKEN`, permissions granted are `org:read`

**Comment by Vovke** [comment]
Previously I've created a token under @paritytech-ci user, but they don't have enough permissions. Need to create token under org.

**Comment by Vovke** [comment]
@TriplEight please take care

**Comment by TriplEight** [comment]
Created a `PRCR_TOKEN` PAT from a user, added it to org secrets. Please tell if it's no sufficient or close the issue.

**Comment by joao-paulo-parity** [comment]
We can reopen this ticket if needed. Closing it.
