### ISSUE TITLE
Check that the pr-custom-review status was generated after the last relevant event

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/pr-custom-review#87]
Problem: We do not check that the pr-custom-review status was generated after the last relevant event, therefore an outdated `Check reviews` success might linger after a PR goes from "Approved" to "Pending" (in case of requested changes).

Consider the following scenario:

- PR has passing `Check reviews` status
- I remove one approval, which _**will**_ make `Check reviews` fail _**eventually**_ after that

The problem is that, even though I have removed the approval, `Check reviews` does not immediately change to "Pending", therefore it will take a while to correct itself (until the action is ran again). i.e. `Check reviews` will be incorrectly left as "Success" until the action is ran again.

Usually the workflow takes a few seconds to finish the action and so this will not be a problem most of the time, but given that pr-custom-review is supposed to focus on security, it might be worthwhile to cover ourselves in this regard as well.

Solution: require that the workflows' auto-generated statuses (for us those are `Assign reviewers / pr-custom-review (pull_request)` and `Assign reviewers / pr-custom-review (pull_request_review)`) are also passing. This should work because those workflows should be moved to "Pending" while they are generating the `Check reviews` status, therefore filling the gap for the momentarily outdated `Check reviews`.

**Comment by TriplEight** [comment]
Yeah, good point. But WDYT maybe it's better to relaunch the checks on every relevant event trigger/webhook?
This will have to be configured in the GHA config yaml tho, which (1) will be prone to human error and (2) not sure if we choose GHA for PRCR to move forward.

**Comment by joao-paulo-parity** [comment]
> This will have to be configured in the GHA config yaml tho, which (1) will be prone to human error and (2) not sure if we choose GHA for PRCR to move forward.

By "require that the workflows' auto-generated statuses" I mean requiring them in the repository settings. At least that's the only way I know of enforcing that certain statuses should be passing.

**Comment by TriplEight** [comment]
Yeah, thanks for explaining. This would be a better and easier fix. So I'll add these jobs as required into the repos.
Also, could you please add this to https://github.com/paritytech/ci_cd/wiki/HowTo:-GitHub-Actions-best-practices and https://github.com/paritytech/ci_cd/wiki/HowTo:-GitHub-Actions-best-practices?

**Comment by joao-paulo-parity** [comment]
@TriplEight sorry, I couldn't infer what's the general advice to take away from this scenario since this problem is specific to how pr-custom-review works
